# Were exploring monitization options but this file will be here if we plan to add funding options
# github: [banakin, seirin-blu, TheRandomGamrTRG]
# custom: ["https://faithfultweaks.com/", faithfultweaks.com]