baseURL = "https://faithfultweaks.com/"
languageCode = "en-us"
title = "Compliance Tweaks"
publishDir = "public"
disableKinds = ["taxonomy", "taxonomyTerm"]

[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = true
