name: Build

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Repository Name In Lower Case
      run: echo REPOSITORY_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

    - name: Build and Push to GitHub Packages Docker Registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: docker.pkg.github.com/${{ env.REPOSITORY_NAME }}/server
        tags: latest
