name: Functions CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: 
      - master
    paths:
      - 'functions/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint_function_pull_request:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: npm ci
        working-directory: functions
      - name: Lint functions
        run: npm run lint
        working-directory: functions
