name: Functions CI

on:
  pull_request:
    branches: 
      - master
    paths:
      - 'functions/**'

jobs:
  lint_functions:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: npm ci
        working-directory: functions
      - name: Lint functions
        run: npm run lint
        working-directory: functions
